[package]
name = "db721-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde_json = "1.0.96"
serde = { version="1.0.163", features=["derive"]}
lazy_static = "1.4.0"